// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tracking.proto

package com.imprexion.service.tracking.bean;

/**
 * Protobuf type {@code tracking.aiscreen}
 */
public  final class aiscreen extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tracking.aiscreen)
    aiscreenOrBuilder {
private static final long serialVersionUID = 0L;
  // Use aiscreen.newBuilder() to construct.
  private aiscreen(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private aiscreen() {
    usrSex_ = 0;
    standHere_ = false;
    isActived_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private aiscreen(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            usrSex_ = input.readInt32();
            break;
          }
          case 16: {

            isActived_ = input.readBool();
            break;
          }
          case 24: {

            standHere_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.imprexion.service.tracking.bean.TrackingMessage.internal_static_tracking_aiscreen_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.imprexion.service.tracking.bean.TrackingMessage.internal_static_tracking_aiscreen_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.imprexion.service.tracking.bean.aiscreen.class, com.imprexion.service.tracking.bean.aiscreen.Builder.class);
  }

  public static final int USR_SEX_FIELD_NUMBER = 1;
  private int usrSex_;
  /**
   * <code>int32 usr_sex = 1;</code>
   */
  public int getUsrSex() {
    return usrSex_;
  }

  public static final int STAND_HERE_FIELD_NUMBER = 3;
  private boolean standHere_;
  /**
   * <code>bool stand_here = 3;</code>
   */
  public boolean getStandHere() {
    return standHere_;
  }

  public static final int IS_ACTIVED_FIELD_NUMBER = 2;
  private boolean isActived_;
  /**
   * <code>bool is_actived = 2;</code>
   */
  public boolean getIsActived() {
    return isActived_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (usrSex_ != 0) {
      output.writeInt32(1, usrSex_);
    }
    if (isActived_ != false) {
      output.writeBool(2, isActived_);
    }
    if (standHere_ != false) {
      output.writeBool(3, standHere_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (usrSex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, usrSex_);
    }
    if (isActived_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, isActived_);
    }
    if (standHere_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, standHere_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.imprexion.service.tracking.bean.aiscreen)) {
      return super.equals(obj);
    }
    com.imprexion.service.tracking.bean.aiscreen other = (com.imprexion.service.tracking.bean.aiscreen) obj;

    boolean result = true;
    result = result && (getUsrSex()
        == other.getUsrSex());
    result = result && (getStandHere()
        == other.getStandHere());
    result = result && (getIsActived()
        == other.getIsActived());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USR_SEX_FIELD_NUMBER;
    hash = (53 * hash) + getUsrSex();
    hash = (37 * hash) + STAND_HERE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getStandHere());
    hash = (37 * hash) + IS_ACTIVED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsActived());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.imprexion.service.tracking.bean.aiscreen parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.imprexion.service.tracking.bean.aiscreen parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.imprexion.service.tracking.bean.aiscreen parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.imprexion.service.tracking.bean.aiscreen parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.imprexion.service.tracking.bean.aiscreen parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.imprexion.service.tracking.bean.aiscreen parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.imprexion.service.tracking.bean.aiscreen parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.imprexion.service.tracking.bean.aiscreen parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.imprexion.service.tracking.bean.aiscreen parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.imprexion.service.tracking.bean.aiscreen parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.imprexion.service.tracking.bean.aiscreen parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.imprexion.service.tracking.bean.aiscreen parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.imprexion.service.tracking.bean.aiscreen prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tracking.aiscreen}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tracking.aiscreen)
      com.imprexion.service.tracking.bean.aiscreenOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.imprexion.service.tracking.bean.TrackingMessage.internal_static_tracking_aiscreen_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.imprexion.service.tracking.bean.TrackingMessage.internal_static_tracking_aiscreen_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.imprexion.service.tracking.bean.aiscreen.class, com.imprexion.service.tracking.bean.aiscreen.Builder.class);
    }

    // Construct using com.imprexion.service.tracking.bean.aiscreen.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      usrSex_ = 0;

      standHere_ = false;

      isActived_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.imprexion.service.tracking.bean.TrackingMessage.internal_static_tracking_aiscreen_descriptor;
    }

    public com.imprexion.service.tracking.bean.aiscreen getDefaultInstanceForType() {
      return com.imprexion.service.tracking.bean.aiscreen.getDefaultInstance();
    }

    public com.imprexion.service.tracking.bean.aiscreen build() {
      com.imprexion.service.tracking.bean.aiscreen result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.imprexion.service.tracking.bean.aiscreen buildPartial() {
      com.imprexion.service.tracking.bean.aiscreen result = new com.imprexion.service.tracking.bean.aiscreen(this);
      result.usrSex_ = usrSex_;
      result.standHere_ = standHere_;
      result.isActived_ = isActived_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.imprexion.service.tracking.bean.aiscreen) {
        return mergeFrom((com.imprexion.service.tracking.bean.aiscreen)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.imprexion.service.tracking.bean.aiscreen other) {
      if (other == com.imprexion.service.tracking.bean.aiscreen.getDefaultInstance()) return this;
      if (other.getUsrSex() != 0) {
        setUsrSex(other.getUsrSex());
      }
      if (other.getStandHere() != false) {
        setStandHere(other.getStandHere());
      }
      if (other.getIsActived() != false) {
        setIsActived(other.getIsActived());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.imprexion.service.tracking.bean.aiscreen parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.imprexion.service.tracking.bean.aiscreen) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int usrSex_ ;
    /**
     * <code>int32 usr_sex = 1;</code>
     */
    public int getUsrSex() {
      return usrSex_;
    }
    /**
     * <code>int32 usr_sex = 1;</code>
     */
    public Builder setUsrSex(int value) {
      
      usrSex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 usr_sex = 1;</code>
     */
    public Builder clearUsrSex() {
      
      usrSex_ = 0;
      onChanged();
      return this;
    }

    private boolean standHere_ ;
    /**
     * <code>bool stand_here = 3;</code>
     */
    public boolean getStandHere() {
      return standHere_;
    }
    /**
     * <code>bool stand_here = 3;</code>
     */
    public Builder setStandHere(boolean value) {
      
      standHere_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool stand_here = 3;</code>
     */
    public Builder clearStandHere() {
      
      standHere_ = false;
      onChanged();
      return this;
    }

    private boolean isActived_ ;
    /**
     * <code>bool is_actived = 2;</code>
     */
    public boolean getIsActived() {
      return isActived_;
    }
    /**
     * <code>bool is_actived = 2;</code>
     */
    public Builder setIsActived(boolean value) {
      
      isActived_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_actived = 2;</code>
     */
    public Builder clearIsActived() {
      
      isActived_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tracking.aiscreen)
  }

  // @@protoc_insertion_point(class_scope:tracking.aiscreen)
  private static final com.imprexion.service.tracking.bean.aiscreen DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.imprexion.service.tracking.bean.aiscreen();
  }

  public static com.imprexion.service.tracking.bean.aiscreen getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<aiscreen>
      PARSER = new com.google.protobuf.AbstractParser<aiscreen>() {
    public aiscreen parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new aiscreen(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<aiscreen> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<aiscreen> getParserForType() {
    return PARSER;
  }

  public com.imprexion.service.tracking.bean.aiscreen getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

