// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tracking.proto

package com.imprexion.service.tracking.bean;

public interface aiscreenOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tracking.aiscreen)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 usr_sex = 1;</code>
   */
  int getUsrSex();

  /**
   * <code>bool stand_here = 3;</code>
   */
  boolean getStandHere();

  /**
   * <code>bool is_actived = 2;</code>
   */
  boolean getIsActived();
}
