// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tracking.proto

package com.imprexion.service.tracking.bean;

/**
 * Protobuf enum {@code tracking.dynamic_gesture}
 */
public enum dynamic_gesture
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>no_dynamic_gesture = 0;</code>
   */
  no_dynamic_gesture(0),
  /**
   * <code>swipe_right = 1;</code>
   */
  swipe_right(1),
  /**
   * <code>swipe_left = 2;</code>
   */
  swipe_left(2),
  /**
   * <code>swipe_up = 3;</code>
   */
  swipe_up(3),
  /**
   * <code>swipe_down = 4;</code>
   */
  swipe_down(4),
  /**
   * <code>waving = 5;</code>
   */
  waving(5),
  /**
   * <code>hold = 6;</code>
   */
  hold(6),
  /**
   * <code>push = 7;</code>
   */
  push(7),
  /**
   * <code>pull = 8;</code>
   */
  pull(8),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>no_dynamic_gesture = 0;</code>
   */
  public static final int no_dynamic_gesture_VALUE = 0;
  /**
   * <code>swipe_right = 1;</code>
   */
  public static final int swipe_right_VALUE = 1;
  /**
   * <code>swipe_left = 2;</code>
   */
  public static final int swipe_left_VALUE = 2;
  /**
   * <code>swipe_up = 3;</code>
   */
  public static final int swipe_up_VALUE = 3;
  /**
   * <code>swipe_down = 4;</code>
   */
  public static final int swipe_down_VALUE = 4;
  /**
   * <code>waving = 5;</code>
   */
  public static final int waving_VALUE = 5;
  /**
   * <code>hold = 6;</code>
   */
  public static final int hold_VALUE = 6;
  /**
   * <code>push = 7;</code>
   */
  public static final int push_VALUE = 7;
  /**
   * <code>pull = 8;</code>
   */
  public static final int pull_VALUE = 8;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static dynamic_gesture valueOf(int value) {
    return forNumber(value);
  }

  public static dynamic_gesture forNumber(int value) {
    switch (value) {
      case 0: return no_dynamic_gesture;
      case 1: return swipe_right;
      case 2: return swipe_left;
      case 3: return swipe_up;
      case 4: return swipe_down;
      case 5: return waving;
      case 6: return hold;
      case 7: return push;
      case 8: return pull;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<dynamic_gesture>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      dynamic_gesture> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<dynamic_gesture>() {
          public dynamic_gesture findValueByNumber(int number) {
            return dynamic_gesture.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.imprexion.service.tracking.bean.TrackingMessage.getDescriptor().getEnumTypes().get(1);
  }

  private static final dynamic_gesture[] VALUES = values();

  public static dynamic_gesture valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private dynamic_gesture(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:tracking.dynamic_gesture)
}

