// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tracking.proto

package com.imprexion.service.tracking.bean;

/**
 * Protobuf type {@code tracking.mouse}
 */
public  final class mouse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tracking.mouse)
    mouseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use mouse.newBuilder() to construct.
  private mouse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private mouse() {
    x_ = 0F;
    y_ = 0F;
    gesture_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private mouse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 13: {

            x_ = input.readFloat();
            break;
          }
          case 21: {

            y_ = input.readFloat();
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            gesture_ = rawValue;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.imprexion.service.tracking.bean.TrackingMessage.internal_static_tracking_mouse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.imprexion.service.tracking.bean.TrackingMessage.internal_static_tracking_mouse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.imprexion.service.tracking.bean.mouse.class, com.imprexion.service.tracking.bean.mouse.Builder.class);
  }

  public static final int X_FIELD_NUMBER = 1;
  private float x_;
  /**
   * <code>float x = 1;</code>
   */
  public float getX() {
    return x_;
  }

  public static final int Y_FIELD_NUMBER = 2;
  private float y_;
  /**
   * <code>float y = 2;</code>
   */
  public float getY() {
    return y_;
  }

  public static final int GESTURE_FIELD_NUMBER = 3;
  private int gesture_;
  /**
   * <code>.tracking.hand_gesture gesture = 3;</code>
   */
  public int getGestureValue() {
    return gesture_;
  }
  /**
   * <code>.tracking.hand_gesture gesture = 3;</code>
   */
  public com.imprexion.service.tracking.bean.hand_gesture getGesture() {
    com.imprexion.service.tracking.bean.hand_gesture result = com.imprexion.service.tracking.bean.hand_gesture.valueOf(gesture_);
    return result == null ? com.imprexion.service.tracking.bean.hand_gesture.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (x_ != 0F) {
      output.writeFloat(1, x_);
    }
    if (y_ != 0F) {
      output.writeFloat(2, y_);
    }
    if (gesture_ != com.imprexion.service.tracking.bean.hand_gesture.none.getNumber()) {
      output.writeEnum(3, gesture_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (x_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, x_);
    }
    if (y_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, y_);
    }
    if (gesture_ != com.imprexion.service.tracking.bean.hand_gesture.none.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, gesture_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.imprexion.service.tracking.bean.mouse)) {
      return super.equals(obj);
    }
    com.imprexion.service.tracking.bean.mouse other = (com.imprexion.service.tracking.bean.mouse) obj;

    boolean result = true;
    result = result && (
        java.lang.Float.floatToIntBits(getX())
        == java.lang.Float.floatToIntBits(
            other.getX()));
    result = result && (
        java.lang.Float.floatToIntBits(getY())
        == java.lang.Float.floatToIntBits(
            other.getY()));
    result = result && gesture_ == other.gesture_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + X_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getX());
    hash = (37 * hash) + Y_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getY());
    hash = (37 * hash) + GESTURE_FIELD_NUMBER;
    hash = (53 * hash) + gesture_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.imprexion.service.tracking.bean.mouse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.imprexion.service.tracking.bean.mouse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.imprexion.service.tracking.bean.mouse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.imprexion.service.tracking.bean.mouse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.imprexion.service.tracking.bean.mouse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.imprexion.service.tracking.bean.mouse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.imprexion.service.tracking.bean.mouse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.imprexion.service.tracking.bean.mouse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.imprexion.service.tracking.bean.mouse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.imprexion.service.tracking.bean.mouse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.imprexion.service.tracking.bean.mouse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.imprexion.service.tracking.bean.mouse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.imprexion.service.tracking.bean.mouse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tracking.mouse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tracking.mouse)
      com.imprexion.service.tracking.bean.mouseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.imprexion.service.tracking.bean.TrackingMessage.internal_static_tracking_mouse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.imprexion.service.tracking.bean.TrackingMessage.internal_static_tracking_mouse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.imprexion.service.tracking.bean.mouse.class, com.imprexion.service.tracking.bean.mouse.Builder.class);
    }

    // Construct using com.imprexion.service.tracking.bean.mouse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      x_ = 0F;

      y_ = 0F;

      gesture_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.imprexion.service.tracking.bean.TrackingMessage.internal_static_tracking_mouse_descriptor;
    }

    public com.imprexion.service.tracking.bean.mouse getDefaultInstanceForType() {
      return com.imprexion.service.tracking.bean.mouse.getDefaultInstance();
    }

    public com.imprexion.service.tracking.bean.mouse build() {
      com.imprexion.service.tracking.bean.mouse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.imprexion.service.tracking.bean.mouse buildPartial() {
      com.imprexion.service.tracking.bean.mouse result = new com.imprexion.service.tracking.bean.mouse(this);
      result.x_ = x_;
      result.y_ = y_;
      result.gesture_ = gesture_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.imprexion.service.tracking.bean.mouse) {
        return mergeFrom((com.imprexion.service.tracking.bean.mouse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.imprexion.service.tracking.bean.mouse other) {
      if (other == com.imprexion.service.tracking.bean.mouse.getDefaultInstance()) return this;
      if (other.getX() != 0F) {
        setX(other.getX());
      }
      if (other.getY() != 0F) {
        setY(other.getY());
      }
      if (other.gesture_ != 0) {
        setGestureValue(other.getGestureValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.imprexion.service.tracking.bean.mouse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.imprexion.service.tracking.bean.mouse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private float x_ ;
    /**
     * <code>float x = 1;</code>
     */
    public float getX() {
      return x_;
    }
    /**
     * <code>float x = 1;</code>
     */
    public Builder setX(float value) {
      
      x_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float x = 1;</code>
     */
    public Builder clearX() {
      
      x_ = 0F;
      onChanged();
      return this;
    }

    private float y_ ;
    /**
     * <code>float y = 2;</code>
     */
    public float getY() {
      return y_;
    }
    /**
     * <code>float y = 2;</code>
     */
    public Builder setY(float value) {
      
      y_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float y = 2;</code>
     */
    public Builder clearY() {
      
      y_ = 0F;
      onChanged();
      return this;
    }

    private int gesture_ = 0;
    /**
     * <code>.tracking.hand_gesture gesture = 3;</code>
     */
    public int getGestureValue() {
      return gesture_;
    }
    /**
     * <code>.tracking.hand_gesture gesture = 3;</code>
     */
    public Builder setGestureValue(int value) {
      gesture_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.tracking.hand_gesture gesture = 3;</code>
     */
    public com.imprexion.service.tracking.bean.hand_gesture getGesture() {
      com.imprexion.service.tracking.bean.hand_gesture result = com.imprexion.service.tracking.bean.hand_gesture.valueOf(gesture_);
      return result == null ? com.imprexion.service.tracking.bean.hand_gesture.UNRECOGNIZED : result;
    }
    /**
     * <code>.tracking.hand_gesture gesture = 3;</code>
     */
    public Builder setGesture(com.imprexion.service.tracking.bean.hand_gesture value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      gesture_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.tracking.hand_gesture gesture = 3;</code>
     */
    public Builder clearGesture() {
      
      gesture_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tracking.mouse)
  }

  // @@protoc_insertion_point(class_scope:tracking.mouse)
  private static final com.imprexion.service.tracking.bean.mouse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.imprexion.service.tracking.bean.mouse();
  }

  public static com.imprexion.service.tracking.bean.mouse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<mouse>
      PARSER = new com.google.protobuf.AbstractParser<mouse>() {
    public mouse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new mouse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<mouse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<mouse> getParserForType() {
    return PARSER;
  }

  public com.imprexion.service.tracking.bean.mouse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

