// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tracking.proto

package com.imprexion.service.tracking.bean;

public interface mouseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tracking.mouse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float x = 1;</code>
   */
  float getX();

  /**
   * <code>float y = 2;</code>
   */
  float getY();

  /**
   * <code>.tracking.hand_gesture gesture = 3;</code>
   */
  int getGestureValue();
  /**
   * <code>.tracking.hand_gesture gesture = 3;</code>
   */
  com.imprexion.service.tracking.bean.hand_gesture getGesture();
}
