// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tracking.proto

package com.imprexion.service.tracking.bean;

public final class TrackingMessage {
  private TrackingMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tracking_aiscreen_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tracking_aiscreen_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tracking_mouse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tracking_mouse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tracking_user_info_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tracking_user_info_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016tracking.proto\022\010tracking\"C\n\010aiscreen\022\017" +
      "\n\007usr_sex\030\001 \001(\005\022\022\n\nstand_here\030\003 \001(\010\022\022\n\ni" +
      "s_actived\030\002 \001(\010\"F\n\005mouse\022\t\n\001x\030\001 \001(\002\022\t\n\001y" +
      "\030\002 \001(\002\022\'\n\007gesture\030\003 \001(\0162\026.tracking.hand_" +
      "gesture\"\360\001\n\tuser_info\022\022\n\nvalid_hand\030\001 \001(" +
      "\005\0225\n\022dynamic_gesture_id\030\002 \001(\0162\031.tracking" +
      ".dynamic_gesture\0222\n\023left_arm_posture_id\030" +
      "\003 \001(\0162\025.tracking.arm_posture\0223\n\024right_ar" +
      "m_posture_id\030\004 \001(\0162\025.tracking.arm_postur" +
      "e\022/\n\017hand_gesture_id\030\005 \001(\0162\026.tracking.ha" +
      "nd_gesture*t\n\014hand_gesture\022\010\n\004none\020\000\022\010\n\004" +
      "palm\020\001\022\010\n\004grab\020\002\022\014\n\010thumb_up\020\003\022\013\n\007victor" +
      "y\020\004\022\020\n\014holding_prog\020\005\022\010\n\004wave\020\006\022\017\n\013risin" +
      "g_hand\020\007*\222\001\n\017dynamic_gesture\022\026\n\022no_dynam" +
      "ic_gesture\020\000\022\017\n\013swipe_right\020\001\022\016\n\nswipe_l" +
      "eft\020\002\022\014\n\010swipe_up\020\003\022\016\n\nswipe_down\020\004\022\n\n\006w" +
      "aving\020\005\022\010\n\004hold\020\006\022\010\n\004push\020\007\022\010\n\004pull\020\010*]\n" +
      "\013arm_posture\022\022\n\016no_arm_posture\020\000\022\020\n\014stai" +
      "ght_high\020\001\022\010\n\004high\020\002\022\010\n\004flat\020\003\022\007\n\003low\020\004\022" +
      "\013\n\007armDown\020\005B8\n#com.imprexion.service.tr" +
      "acking.beanB\017TrackingMessageP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tracking_aiscreen_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tracking_aiscreen_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tracking_aiscreen_descriptor,
        new java.lang.String[] { "UsrSex", "StandHere", "IsActived", });
    internal_static_tracking_mouse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tracking_mouse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tracking_mouse_descriptor,
        new java.lang.String[] { "X", "Y", "Gesture", });
    internal_static_tracking_user_info_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tracking_user_info_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tracking_user_info_descriptor,
        new java.lang.String[] { "ValidHand", "DynamicGestureId", "LeftArmPostureId", "RightArmPostureId", "HandGestureId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
