// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tracking.proto

package com.imprexion.service.tracking.bean;

public interface user_infoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tracking.user_info)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 valid_hand = 1;</code>
   */
  int getValidHand();

  /**
   * <code>.tracking.dynamic_gesture dynamic_gesture_id = 2;</code>
   */
  int getDynamicGestureIdValue();
  /**
   * <code>.tracking.dynamic_gesture dynamic_gesture_id = 2;</code>
   */
  com.imprexion.service.tracking.bean.dynamic_gesture getDynamicGestureId();

  /**
   * <code>.tracking.arm_posture left_arm_posture_id = 3;</code>
   */
  int getLeftArmPostureIdValue();
  /**
   * <code>.tracking.arm_posture left_arm_posture_id = 3;</code>
   */
  com.imprexion.service.tracking.bean.arm_posture getLeftArmPostureId();

  /**
   * <code>.tracking.arm_posture right_arm_posture_id = 4;</code>
   */
  int getRightArmPostureIdValue();
  /**
   * <code>.tracking.arm_posture right_arm_posture_id = 4;</code>
   */
  com.imprexion.service.tracking.bean.arm_posture getRightArmPostureId();

  /**
   * <code>.tracking.hand_gesture hand_gesture_id = 5;</code>
   */
  int getHandGestureIdValue();
  /**
   * <code>.tracking.hand_gesture hand_gesture_id = 5;</code>
   */
  com.imprexion.service.tracking.bean.hand_gesture getHandGestureId();
}
